FROM alpine:3.6
MAINTAINER sparklyballs

# install packages
RUN \
 apk add --no-cache \
	bash \
	bzip2 \
	coreutils \
	git \
	gzip \
	imagemagick \
	librsvg \
	tar \
	util-linux && \

 apk add --no-cache \
	--repository http://nl.alpinelinux.org/alpine/edge/community \
	pngquant

# copy build script
COPY root/ /

# build picons
RUN \
 mkdir -p \
	/picons \
	/usr/src/temp-output && \
 /bin/bash /build-picons.sh

CMD ["cp", "-avr", "/picons/picons.tar.bz2", "/mnt/"]
