FROM alpine:3.4
MAINTAINER sparklyballs

# copy build script
COPY root/ /

# install packages
RUN \
 apk add --no-cache \
	bash \
	coreutils \
	git \
	gzip \
	imagemagick \
	librsvg \
	tar \
	util-linux && \

 apk add --no-cache \
	--repository http://nl.alpinelinux.org/alpine/edge/testing \
	pngquant

# build picons
RUN \
 /bin/bash /build-picons.sh

CMD ["cp", "-avr", "/usr/src/picons-source/build-output", "/mnt/"]
