name: Picons Builder

on:
  schedule:
    - cron:  '20 17 * * 3'
  workflow_dispatch:

jobs:
  picons_builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Build image
        run: |
          docker build --no-cache -t ghcr.io/linuxserver/picons-builder:latest .
      - name: Tag image
        if: ${{ github.ref == format('refs/heads/master') }}
        run: |
          docker tag ghcr.io/linuxserver/picons-builder:latest ghcr.io/linuxserver/picons-builder:$(date +%F)
      - name: Login to GitHub Container Registry
        if: ${{ github.ref == format('refs/heads/master') && env.CR_USER && env.CR_PAT }}
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ secrets.CR_USER }} --password-stdin
      - name: Push tags to GitHub Container Registry
        if: ${{ github.ref == format('refs/heads/master') && env.CR_USER && env.CR_PAT }}
        run: |
          docker push ghcr.io/linuxserver/picons-builder:$(date +%F)
          docker push ghcr.io/linuxserver/picons-builder:latest
